import type { KPICard, CameraLocation, HeatmapPoint, AlertRow, TimelineEvent } from "@/types";

export const kpiCards: KPICard[] = [
  {
    id: "active-cameras",
    label: "ACTIVE CAMERAS",
    value: "7 / 7",
    iconName: "Camera",
    delta: "+0%",
    deltaType: "up",
    deltaLabel: "all operational",
    accentColor: "#3B82F6",
    barData: [6, 6, 7, 7, 7, 7, 7],
  },
  {
    id: "threat-events",
    label: "THREAT EVENTS (24H)",
    value: 23,
    iconName: "ShieldAlert",
    delta: "-12%",
    deltaType: "down",
    deltaLabel: "vs yesterday",
    accentColor: "#EF4444",
    barData: [12, 18, 14, 28, 22, 19, 23],
  },
  {
    id: "tracked-persons",
    label: "TRACKED IDENTITIES",
    value: 12,
    iconName: "Users",
    delta: "+3",
    deltaType: "up",
    deltaLabel: "re-id targets",
    accentColor: "#8B5CF6",
    barData: [4, 7, 8, 9, 10, 11, 12],
  },
  {
    id: "acoustic-sensors",
    label: "ACOUSTIC SENSORS",
    value: "100%",
    iconName: "Volume2",
    delta: "ACTIVE",
    deltaType: "up",
    deltaLabel: "sentry listening",
    accentColor: "#10B981",
    barData: [98, 99, 100, 100, 100, 100, 100],
  },
];

export const cameraLocations: CameraLocation[] = [
  {
    id: "CAM_01_GATE_NORTH",
    name: "North Gate Perimeter",
    lat: 31.6200,
    lng: 74.8700,
    riskScore: 78,
    threatLevel: "high",
    status: "online",
    lastActivity: "12s ago",
  },
  {
    id: "CAM_02_LOBBY",
    name: "Plaza Main Reception",
    lat: 31.6230,
    lng: 74.8720,
    riskScore: 42,
    threatLevel: "medium",
    status: "online",
    lastActivity: "2s ago",
  },
  {
    id: "CAM_03_CORRIDOR_1F",
    name: "East Corridor & Passage",
    lat: 31.6250,
    lng: 74.8750,
    riskScore: 24,
    threatLevel: "low",
    status: "online",
    lastActivity: "45s ago",
  },
  {
    id: "CAM_04_SERVER_ROOM",
    name: "Server Vault & Storage",
    lat: 31.6210,
    lng: 74.8690,
    riskScore: 88,
    threatLevel: "critical",
    status: "online",
    lastActivity: "Just now",
  },
];

export const heatmapPoints: HeatmapPoint[] = [
  { lat: 31.6200, lng: 74.8700, intensity: 0.8 },
  { lat: 31.6230, lng: 74.8720, intensity: 0.4 },
  { lat: 31.6250, lng: 74.8750, intensity: 0.2 },
  { lat: 31.6210, lng: 74.8690, intensity: 0.9 },
  { lat: 31.6280, lng: 74.8790, intensity: 0.5 },
];

export const alertRows: AlertRow[] = [
  {
    id: "ALT-1092",
    time: "14:32:10",
    event: "Virtual Fence Tripwire Breached",
    sector: "Sector 4",
    severity: "critical",
    status: "Active",
    iconType: "person",
  },
  {
    id: "ALT-1091",
    time: "14:28:45",
    event: "Watchlist Suspect Identified (PERSON_001)",
    sector: "Sector 1",
    severity: "high",
    status: "Investigating",
    iconType: "watchlist",
  },
  {
    id: "ALT-1090",
    time: "14:15:20",
    event: "Harmonic Acoustic UAV BPF Detected (168 Hz)",
    sector: "Sector 2",
    severity: "high",
    status: "Investigating",
    iconType: "drone",
  },
  {
    id: "ALT-1089",
    time: "13:58:02",
    event: "Unauthorized Vehicle ANPR Entry",
    sector: "Sector 1",
    severity: "medium",
    status: "Resolved",
    iconType: "vehicle",
  },
  {
    id: "ALT-1088",
    time: "13:42:15",
    event: "Loitering Event Near Data Vault",
    sector: "Sector 4",
    severity: "medium",
    status: "Resolved",
    iconType: "person",
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "EV-01",
    time: "14:32",
    title: "Virtual Fence Intrusion Alert",
    description: "Subject crossed restricted yellow fence perimeter on CAM_04.",
    type: "intrusion",
    severity: "critical",
    dotColor: "#EF4444",
  },
  {
    id: "EV-02",
    time: "14:28",
    title: "Watchlist Match: PERSON_001",
    description: "Cosine similarity 0.998 on North Gate Entry CAM_01.",
    type: "watchlist",
    severity: "high",
    dotColor: "#F97316",
  },
  {
    id: "EV-03",
    time: "14:15",
    title: "Acoustic Drone Sentry Rotor Hit",
    description: "Classified DJI Phantom / Mavic harmonic rotor signature.",
    type: "drone",
    severity: "high",
    dotColor: "#F97316",
  },
  {
    id: "EV-04",
    time: "13:58",
    title: "License Plate Captured",
    description: "Vehicle logged at North Checkpoint Gate with ANPR.",
    type: "vehicle",
    severity: "medium",
    dotColor: "#EAB308",
  },
];
